 -- 1
 SELECT STUDENT_NAME "학생이름", STUDENT_ADDRESS "주소지" FROM TB_STUDENT
 ORDER BY STUDENT_NAME;
 
 -- 2
 SELECT STUDENT_NAME, STUDENT_SSN FROM TB_STUDENT WHERE ABSENCE_YN = 'Y'
 ORDER BY STUDENT_SSN DESC;
 
 -- 3
 SELECT STUDENT_NAME "학생이름", STUDENT_NO "학번", STUDENT_ADDRESS "거주지 주소" FROM TB_STUDENT
 WHERE STUDENT_NO NOT LIKE '%A%' AND STUDENT_ADDRESS LIKE ('%경기도%')
 ORDER BY STUDENT_NAME;
 
 -- 4
 SELECT PROFESSOR_NAME, PROFESSOR_SSN FROM TB_PROFESSOR WHERE DEPARTMENT_NO = '005'
 ORDER BY PROFESSOR_SSN;
 
 -- 5
 SELECT STUDENT_NO, POINT 
 FROM TB_STUDENT , TB_GRADE ;
 
 -- 6
 SELECT STUDENT_NO , STUDENT_NAME , DEPARTMENT_NAME 
 FROM TB_STUDENT S, TB_DEPARTMENT D
 WHERE S.DEPARTMENT_NO = D.DEPARTMENT_NO
 ORDER BY STUDENT_NAME;
 
 -- 7
SELECT CLASS_NAME, DEPARTMENT_NAME 
FROM TB_CLASS C, TB_DEPARTMENT D
WHERE C.DEPARTMENT_NO = D.DEPARTMENT_NO
ORDER BY DEPARTMENT_NAME;

-- 8
SELECT CLASS_NAME, PROFESSOR_NAME
FROM TB_CLASS C, TB_PROFESSOR P
WHERE C.DEPARTMENT_NO = P.DEPARTMENT_NO;

-- 9


 
 
 