// 1 
SELECT DEPARTMENT_NAME, CATEGORY
FROM TB_DEPARTMENT;

// 2
SELECT DEPARTMENT_NAME ||'의 정원은 '|| CAPACITY || '명 입니다.' 
FROM TB_DEPARTMENT;

// 3 ..?
SELECT DEPARTMENT_NAME, STUDENT_NAME FROM TB_DEPARTMENT, TB_STUDENT WHERE ABSENCE_YN IS NULL;

// 4 : 학번 1개 입력했을땐 정상적으로 출력, 여러개 입력했을때는 오류
SELECT STUDENT_NAME FROM TB_STUDENT WHERE STUDENT_NO LIKE ('A513090');

// 5
SELECT DEPARTMENT_NAME, CATEGORY
FROM TB_DEPARTMENT WHERE CAPACITY BETWEEN 20 AND 30;

// 6
