 -- 1
 SELECT STUDENT_NO, STUDENT_NAME, ENTRANCE_DATE FROM TB_STUDENT WHERE DEPARTMENT_NO = '002'
 ORDER BY ENTRANCE_DATE;
 
 -- 2
 SELECT PROFESSOR_NAME, PROFESSOR_SSN FROM TB_PROFESSOR WHERE LENGTH(PROFESSOR_NAME) != '3';
 
 -- 3
 SELECT PROFESSOR_NAME, (100 - SUBSTR (PROFESSOR_SSN, 1, 2 )+23) -1 as "나이"
 FROM TB_PROFESSOR WHERE SUBSTR (PROFESSOR_SSN, 8, 1) = 1
 ORDER BY "나이";
 
 -- 4
SELECT PROFESSOR_NAME, SUBSTR(PROFESSOR_NAME, 2,3 ) "이름" FROM TB_PROFESSOR;

 -- 5

 
 -- 6
 SELECT 
 TO_CHAR((TO_DATE(20201225)),'day') FROM DUAL;
 
 -- 7
 SELECT TO_CHAR(TO_DATE('99/10/11') , 'YYYY/MM/DD') FROM DUAL;

 -- 8
SELECT STUDENT_NO, STUDENT_NAME FROM TB_STUDENT WHERE STUDENT_NO NOT LIKE '%A%';

 -- 9
SELECT ROUND(AVG(POINT),1)"평점" FROM TB_GRADE WHERE STUDENT_NO = 'A517178';

 -- 10
SELECT (STUDENT_NO, DEPARTMENT_NO )"학생수"  FROM TB_STUDENT;


 
