 -- 1
 SELECT STUDENT_NO, STUDENT_NAME, ENTRANCE_DATE FROM TB_STUDENT WHERE DEPARTMENT_NO = '002'
 ORDER BY ENTRANCE_DATE;
 
 -- 2
 SELECT PROFESSOR_NAME, PROFESSOR_SSN FROM TB_PROFESSOR WHERE LENGTH(PROFESSOR_NAME) != '3';
 
 -- 3
 SELECT PROFESSOR_NAME, SUBSTR(PROFESSOR_SSN, 1, 2 )
 FROM TB_PROFESSOR WHERE SUBSTR (PROFESSOR_SSN, 8, 1) = 1;

 -- 4
SELECT PROFESSOR_NAME, SUBSTR(PROFESSOR_NAME, 2,3 ) "이름" FROM TB_PROFESSOR;

 -- 5
 
 
 -- 6
 SELECT 
 TO_CHAR((TO_DATE(20201225)),'day') FROM DUAL;
 
 -- 7

 -- 8
SELECT STUDENT_NO, STUDENT_NAME FROM TB_STUDENT WHERE STUDENT_NO NOT LIKE '%A%';

SELECT AVG(POINT)"평점" FROM TB_GRADE WHERE STUDENT_NO = 'A517178';
 
 
