CREATE SEQUENCE SEQ_MATCHINGTEXT_POST; -- 매칭글SEQ
CREATE SEQUENCE SEQ_MATCHINGTEXTLIKE_LIKE; -- 매칭글좋아요SEQ 
CREATE SEQUENCE SEQ_CHATROOM_NUMBER; -- 채팅방번호(채팅)

DROP SEQUENCE SEQ_MATCHINGTEXT_POST;
DROP SEQUENCE SEQ_MATCHINGTEXTLIKE_LIKE;
DROP SEQUENCE SEQ_CHATROOM_NUMBER;


 CREATE TABLE CHAT (  ---------------------------------------------------------- 채팅
    CHATROOM_SEQ NUMBER,                           -- 채팅방 번호   
    CHAT_STARTDATE DATE DEFAULT SYSDATE,           -- 대화시작날짜시간
    CHAT_ENDDATE DATE DEFAULT SYSDATE              -- 대화종료날짜시간
);
SELECT * FROM CHAT;
DROP TABLE CHAT;


CREATE TABLE CHAT_USER_INFO (  ------------------------------------------------- 채팅참여유저정보
    CHATROOM_SEQ NUMBER,                                        -- 채팅방번호
    CHAT_USERID VARCHAR2(50),                                   -- 채팅발송유저아이디
    CHAT_CONTENT VARCHAR2(300),                                 -- 채팅내용
    CHAT_SENTTIME TIMESTAMP,                                    -- 발송시각
    READ_STATUS VARCHAR2(1) DEFAULT 'N' CHECK(READ_STATUS IN('Y', 'N'))          -- 읽음표시(Y/N)
);
SELECT * FROM CHAT_USER_INFO;
DROP TABLE CHAT_USER_INFO;

CREATE TABLE MATCHING_POST (    ---------------------------------  매칭글
    MATCHING_POST_SEQ NUMBER,
    MATCHING_POST_TITLE VARCHAR2(100) NOT NULL,             -- 매칭글제목
    MATCHING_POST_CONTENT VARCHAR2(3000) NOT NULL,          -- 매칭글내용
    MATCHING_POST_POST_TIME TIMESTAMP,                      -- 매칭글작성시각
    MATCHING_POST_VIEWS NUMBER,                             -- 매칭글조회수
    MATCHING_POST_URL VARCHAR2(200) NOT NULL,               -- 매칭글주소
    MATCHING_ACCEPT VARCHAR(1) DEFAULT 'N' CHECK(MATCHING_ACCEPT IN('Y', 'N')),                          -- 매칭승락(Y/N)
    NOTICE VARCHAR(1) DEFAULT 'N' CHECK(NOTICE IN('Y', 'N')),    -- 공지사항(Y/N) 
    CATEGORY_SEQ NUMBER
);
SELECT * FROM MATCHING_POST;
DROP TABLE MATCHING_POST;

CREATE TABLE MATCHING_POST_LIKE (  ------------------------------------ 매칭글좋아요
    MATCHING_POST_LIKE_SEQ NUMBER,
    LIKE_TIME TIMESTAMP,                                      -- 매칭글좋아요누른시간
    MATCHING_POST_SEQ NUMBER,
    MATCHING_POST_LIKE_USER VARCHAR2(50)                     -- 아이디
);
SELECT * FROM MATCHING_POST_LIKE;
DROP TABLE MATCHING_POST_LIKE;

-- PK ----
ALTER TABLE CHAT ADD CONSTRAINT CHATROOM_NO_PK PRIMARY KEY(CHATROOM_SEQ); -- 채팅(채팅방번호)
ALTER TABLE CHAT_USER_INFO ADD CONSTRAINT CHATROOM_NO_PK PRIMARY KEY(CHATROOM_SEQ); -- 채팅참여유저정보(채팅방번호)
ALTER TABLE MATCHING_POST ADD CONSTRAINT MATCHING_POST_NO_PK PRIMARY KEY(MATCHING_POST_SEQ); -- 매칭글(매칭글SEQ)
ALTER TABLE MATCHING_POST_LIKE ADD CONSTRAINT MATCHING_POST_LIKE_NO_PK PRIMARY KEY(MATCHING_POST_LIKE_SEQ); -- 매칭글좋아요(매칭글좋아요SEQ)





ALTER TABLE MATCHING_POST ADD CONSTRAINT USER_ID_FK FOREIGN KEY(CATEGORY_SEQ) REFERENCES CATEGORY;   --  매칭글(카테고리SEQ)
ALTER TABLE MATCHINGTEXT ADD CONSTRAINT USER_ID_FK FOREIGN KEY(AUTHORUSERID) REFERENCES USERINFO;   -- 매칭글(작성자아디)

ALTER TABLE MATCHINGTEXTLIKE ADD CONSTRAINT MATCHINGTEXT_POST_FK FOREIGN KEY(MATCHINGTEXTLIKE) REFERENCES MATCHINGTEXT; -- 매칭글좋아요(매칭글SEQ)
ALTER TABLE MATCHINGTEXTLIKE ADD CONSTRAINT USERID_FK FOREIGN KEY(MATCHINGTEXTLIKE_LIKE) REFERENCES USERINFO; -- 매칭글좋아요(아이디) 

ALTER TABLE CHATUSERINFO ADD CONSTRAINT FK_CHATUSERINFO_CHATROOM FOREIGN KEY(CHATROOM_NUMBER) REFERENCES CHAT; -- 채팅참여유저정보(채팅방번호)
ALTER TABLE CHATUSERINFO ADD CONSTRAINT CHAT_USERID_FK FOREIGN KEY(CHATUSERINFO) REFERENCES USER_INFO; -- 채팅참여유저정보(참여유저아이디)

